stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

test-job:    # This job runs in the test stage, which runs first.
  stage: test
  image: python:3.11-slim
  script:
    - pip install -U pip
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py test

# build-job:    # This job runs in the build stage.   
#   stage: build  # It only starts when the job in the test stage completes successfully.
#   script:
#     - echo "Compiling the code..."
#     - echo "Compile complete."


# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
